print("Installation will now begin...")
sleep(1)
print("Deleting pre-existing files...")
shell.run("delete", "/startup.lua")
shell.run("delete", "/back.lua")
shell.run("delete", "/os")
print("------------------------------")
sleep(1)
print("Installing new files...")
shell.run("cp", "/disk/Files/startup.lua", "/startup.lua")
shell.run("cp", "/disk/Files/back.lua", "/back.lua")
shell.run("cp", "/disk/Files/os", "/os")
print("------------------------------")
sleep(1)
print("Rebooting...")
sleep(1)
shell.run("/eject.lua")
