shell.run("delete", "/install.lua")
shell.run("delete", "/eject.lua")
shell.run("cp", "/disk/install.lua", "/install.lua")
shell.run("cp", "/disk/eject.lua", "/eject.lua")
term.clear()
term.setCursorPos(1,1)
print("Welcome to CloudOS Installation Program")
print("Type 'install' if you want to install or re-install CloudOS.")
print("Type 'eject' if you want to exit Installation.")
